# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5597cb574805a27b346bdbc552eab463125993060417fc20df167c84496aef0765e614a54b71c05f6787f5a7414171e702ee80a27573ae1c8b0913f37e0558eb

test:
  secret_key_base: 955ec11ca43aed40bf9f90cbf1b4298f778e24e63e5cf2b6b3883146f0cd47c9d5b1e2855132f850fda0007eb8c9823289d97215015a67c0e6bf7b2f52d276da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
